allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  react-intl-universal: true

ignoredBuiltDependencies:
  - electron-winstaller
  - esbuild
  - react-intl-universal

onlyBuiltDependencies:
  - electron
